### ISSUE TITLE
Hardware and Technology

### ISSUE THREAD

**Issue by chorman0773** [lcs-project/secretariat#4]
### Draft Number

4

### LCS Leads Sponsor

rdrpenguin04

### Canonical Location

https://github.com/lcs-project/governance-and-membership/blob/main/drafts/LCSD4.md

**Comment by chorman0773** [comment]
This is a request under §3.2 of SRC SP1.

**Comment by rdrpenguin04** [comment]
The LCS Leads are likely to approve this despite the formal review process not being completed. This is a critical working group and should exist as soon as reasonable.

Sorry I was so late to this; school got in the way
